kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker-train
spec:
  selector:
    matchLabels:
      app: kafka-train
      id: "0"
  template:
    metadata:
      labels:
        app: kafka-train
        id: "0"
    spec:
      containers:
      - name: kafka-train
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka-service-train
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo2:2181
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_CREATE_TOPICS
          value: "models-to-fit:1:1,models-fitted:1:1"
--- 
apiVersion: v1
kind: Service
metadata:
  name: kafka-service-train
  labels:
    name: kafka
spec:
  ports:
  - port: 9092
    name: kafka-port
    protocol: TCP
  selector:
    app: kafka-train
    id: "0"
  type: LoadBalancer

