apiVersion: apps/v1
kind: Deployment
metadata:
  name: trainer
spec:
  selector:
    matchLabels:
      app: trainer
  replicas: 1
  template:
    metadata:
      labels:
        app: trainer
    spec:
      containers:
        - name: trainer
          image: coletyl/trainer
          ports:
            - containerPort: 9999

---

apiVersion: v1
kind: Service
metadata:
  name: trainer-model-service
spec:
  selector:
    app: trainer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9999

---

